version: '3.8'

services:
  mcp-agent-client:
    ports:
      - "8001:8000"  # Use different port to avoid conflicts
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./:/app:ro  # Mount entire project for development
    command: ["uvicorn", "mcp_agent_client:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  mcp-eda-server:
    ports:
      - "8002:8001"  # Use different port for MCP EDA server
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./:/app:ro  # Mount entire project for development
    command: ["python3", "server/mcp/mcp_eda_server.py", "--port", "8001"]

  mcp-servers:
    ports:
      - "14333:13333"  # Synthesis Setup
      - "14334:13334"  # Synthesis Compile
      - "14335:13335"  # Floorplan
      - "14336:13336"  # Power Planning
      - "14337:13337"  # Placement
      - "14338:13338"  # CTS
      - "14339:13339"  # Routing
      - "14440:13440"  # Save Design
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./:/app  # Mount entire project for development
    command: >
      sh -c "
        echo 'Starting MCP servers in debug mode...' &&
        python3 server/synth_setup_server.py --port 13333 --debug &
        python3 server/synth_compile_server.py --port 13334 --debug &
        python3 server/floorplan_server.py --port 13335 --debug &
        python3 server/powerplan_server.py --port 13336 --debug &
        python3 server/placement_server.py --port 13337 --debug &
        python3 server/cts_server.py --port 13338 --debug &
        python3 server/route_server.py --port 13339 --debug &
        python3 server/save_server.py --port 13440 --debug &
        wait
      " 

  experiment-runner:
    volumes:
      - ./:/app  # Mount entire project for development
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    profiles:
      - experiment

  test-runner:
    volumes:
      - ./:/app  # Mount entire project for development
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    profiles:
      - test 