# Auto-generated by generate_openram_srams.py
word_size = 64
num_words = 256


num_rw_ports = 1
num_r_ports = 0
num_w_ports = 0

tech_name = "freepdk45"
nominal_corner_only = False
use_specified_corners = [("FF", 1.25, 0), ("TT", 1.1, 25), ("SS", .95, 125), ("TT", 1., 25)]

route_supplies = False
check_lvsdrc = False
perimeter_pins = False

num_threads = 4

output_name = "sram_{0}rw{1}r{2}w_{3}_{4}_{5}".format(num_rw_ports,
                                                      num_r_ports,
                                                      num_w_ports,
                                                      word_size,
                                                      num_words,
                                                      tech_name)
output_path = "macro/{}".format(output_name)