###############################################################
#  Generated by:      Cadence Innovus 21.17-s075_1
#  OS:                Linux x86_64(Host ID hl279-cmp-00.egr.duke.edu)
#  Generated on:      Tue Jun 17 00:38:49 2025
#  Design:            des3
#  Command:           saveDesign pnr_save/detail_route.enc
###############################################################
current_design des3
create_clock [get_ports {clk}]  -name clk -period 1.000000 -waveform {0.000000 0.500000}
set_propagated_clock  [get_ports {clk}]
set_max_capacitance 5  [get_designs {des3}]
set_max_fanout 10  [get_designs {des3}]
set_max_transition 0.5  [get_designs {des3}]
